# CycloneDDS / ROS2 tuning for large messages (e.g., PointCloud2)
net.core.rmem_max=26214400
net.core.rmem_default=26214400
net.ipv4.ipfrag_high_thresh=134217728
net.ipv4.ipfrag_low_thresh=67108864
net.ipv4.ipfrag_time=3
