#!/usr/bin/env python3
"""Plot ACT front/wrist camera gates from a Door DP jsonl log.

Example:
  python high-level/dp/plot_camera_gates_from_dp_log.py \
    --log high-level/logs/gating_debug/a2w_gate_trace.jsonl \
    --env_id 0 \
    --out high-level/logs/gating_debug/a2w_gate_trace_env0.png
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--log", required=True, type=Path, help="Door DP jsonl log generated by --dp_log_path.")
    parser.add_argument("--env_id", type=int, default=0, help="Controlled env id to plot.")
    parser.add_argument("--out", type=Path, default=None, help="Output png path. Defaults next to the log.")
    parser.add_argument("--show", action="store_true", help="Show the matplotlib window after saving.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if not args.log.exists():
        raise FileNotFoundError(args.log)

    steps: list[int] = []
    front: list[float] = []
    wrist: list[float] = []
    gate_sum: list[float] = []
    phase_names: list[str] = []

    with args.log.open("r", encoding="utf-8") as f:
        for line in f:
            if not line.strip():
                continue
            record = json.loads(line)
            if int(record.get("controlled_env_id", -1)) != int(args.env_id):
                continue
            gates = record.get("camera_gates")
            if not gates:
                continue
            steps.append(int(record["step"]))
            front.append(float(gates["front"]))
            wrist.append(float(gates["wrist"]))
            gate_sum.append(float(gates.get("sum", float(gates["front"]) + float(gates["wrist"]))))
            phase_names.append(str(record.get("phase_name", "")))

    if not steps:
        raise RuntimeError(
            f"No camera_gates found for env_id={args.env_id} in {args.log}. "
            "Make sure the checkpoint was trained with --policy.camera_input_gating=true "
            "and the play command was run after the logging patch."
        )

    import matplotlib.pyplot as plt

    out = args.out
    if out is None:
        out = args.log.with_name(f"{args.log.stem}_camera_gates_env{args.env_id}.png")
    out.parent.mkdir(parents=True, exist_ok=True)

    fig, ax = plt.subplots(figsize=(12, 4.8), constrained_layout=True)
    ax.plot(steps, front, label="g_front", linewidth=1.8)
    ax.plot(steps, wrist, label="g_wrist", linewidth=1.8)
    ax.plot(steps, gate_sum, label="g_front + g_wrist", linestyle="--", linewidth=1.2, alpha=0.75)
    ax.axhline(1.0, color="gray", linewidth=0.8, linestyle=":", alpha=0.8)
    ax.axhline(2.0, color="gray", linewidth=0.8, linestyle=":", alpha=0.6)
    ax.set_title(f"ACT camera input gates from {args.log.name} / env {args.env_id}")
    ax.set_xlabel("simulation step")
    ax.set_ylabel("gate value")
    ax.grid(True, alpha=0.25)
    ax.legend(loc="best")

    # Mark phase changes lightly, useful when the log contains scripted or dp phase labels.
    last_phase = None
    for step, phase in zip(steps, phase_names):
        if phase and phase != last_phase:
            ax.axvline(step, color="black", linewidth=0.5, alpha=0.15)
            last_phase = phase

    fig.savefig(out, dpi=180)
    print(f"Saved camera gate plot: {out}")
    print(
        "summary: "
        f"front min/mean/max={min(front):.4f}/{sum(front)/len(front):.4f}/{max(front):.4f}, "
        f"wrist min/mean/max={min(wrist):.4f}/{sum(wrist)/len(wrist):.4f}/{max(wrist):.4f}, "
        f"n={len(steps)}"
    )
    if args.show:
        plt.show()


if __name__ == "__main__":
    main()
